package com.raishxn.gtna.data.lang;

import com.raishxn.gtna.data.GTNALangProvider;

/**
 * Forge of Gods GUI strings from GTNH TecTech en_US.lang (GT5-Unofficial a3e1e112, LGPL-3.0), generated by
 * tools/extract_godforge_lang.py. Do not edit by hand.
 */
public final class GodforgeLang {

    private GodforgeLang() {}

    public static void add(GTNALangProvider provider) {
        provider.add("gtna.godforge.upgrade.confirm", "Construct");
        provider.add("gtna.godforge.upgrade.respec", "Respec");
        provider.add("gtna.godforge.upgrade.tt.0", "Forge of the Gods");
        provider.add("gtna.godforge.upgrade.tt.1", "Improved Gravitational Convection Coils");
        provider.add("gtna.godforge.upgrade.tt.2", "Spacetime Topology Expansion Modulator");
        provider.add("gtna.godforge.upgrade.tt.3", "Cosmic Fuel Chamber Expansion");
        provider.add("gtna.godforge.upgrade.tt.4", "Graviton-Induced Superconductivity System");
        provider.add("gtna.godforge.upgrade.tt.5", "Fluid Dynamics Integration Module");
        provider.add("gtna.godforge.upgrade.tt.6", "Superluminal Amplifier");
        provider.add("gtna.godforge.upgrade.tt.7", "Gravitational Plasma Containment Inductor");
        provider.add("gtna.godforge.upgrade.tt.8", "Relativistic Electron Capacitor");
        provider.add("gtna.godforge.upgrade.tt.9", "Graviton Entanglement Modulator");
        provider.add("gtna.godforge.upgrade.tt.10", "Closed Timelike Curve Disruption Device");
        provider.add("gtna.godforge.upgrade.tt.11", "Quark-Gluon Plasma Isolation Unit");
        provider.add("gtna.godforge.upgrade.tt.12", "Singularity Exposure Fuel Compression Process");
        provider.add("gtna.godforge.upgrade.tt.13", "Transfinite Construction Techniques");
        provider.add("gtna.godforge.upgrade.tt.14", "Gravitationally Guided Electron Beam Emitter");
        provider.add("gtna.godforge.upgrade.tt.15", "Temporal Plasma Transformation Process");
        provider.add("gtna.godforge.upgrade.tt.16", "Duplicity of Potency");
        provider.add("gtna.godforge.upgrade.tt.17", "Critical Neutrino Tunnelling Integration");
        provider.add("gtna.godforge.upgrade.tt.18", "Extreme Pulsar Exposure Chambers");
        provider.add("gtna.godforge.upgrade.tt.19", "Internal Micro-Kugelblitz Generator");
        provider.add("gtna.godforge.upgrade.tt.20", "Neutron Degeneracy Pressure Exposure");
        provider.add("gtna.godforge.upgrade.tt.21", "Parity of Singularity");
        provider.add("gtna.godforge.upgrade.tt.22", "Disparity of Rarity");
        provider.add("gtna.godforge.upgrade.tt.23", "Null-Gravity Modulation Sheath");
        provider.add("gtna.godforge.upgrade.tt.24", "Synthetic Element Decay Stabilization");
        provider.add("gtna.godforge.upgrade.tt.25", "Paradoxical Attainment");
        provider.add("gtna.godforge.upgrade.tt.26", "Cosmically Duplicate");
        provider.add("gtna.godforge.upgrade.tt.27", "Transfinite Stellar Existence");
        provider.add("gtna.godforge.upgrade.tt.28", "The Boundless Flow");
        provider.add("gtna.godforge.upgrade.tt.29", "Effortless Existence");
        provider.add("gtna.godforge.upgrade.tt.30", "Orion’s Arm Genesis Schema");
        provider.add("gtna.godforge.upgrade.tt.secret", "Secret Upgrade");
        provider.add("gtna.godforge.upgrade.tt.short.0", "START");
        provider.add("gtna.godforge.upgrade.tt.short.1", "IGCC");
        provider.add("gtna.godforge.upgrade.tt.short.2", "STEM");
        provider.add("gtna.godforge.upgrade.tt.short.3", "CFCE");
        provider.add("gtna.godforge.upgrade.tt.short.4", "GISS");
        provider.add("gtna.godforge.upgrade.tt.short.5", "FDIM");
        provider.add("gtna.godforge.upgrade.tt.short.6", "SA");
        provider.add("gtna.godforge.upgrade.tt.short.7", "GPCI");
        provider.add("gtna.godforge.upgrade.tt.short.8", "REC");
        provider.add("gtna.godforge.upgrade.tt.short.9", "GEM");
        provider.add("gtna.godforge.upgrade.tt.short.10", "CTCDD");
        provider.add("gtna.godforge.upgrade.tt.short.11", "QGPIU");
        provider.add("gtna.godforge.upgrade.tt.short.12", "SEFCP");
        provider.add("gtna.godforge.upgrade.tt.short.13", "TCT");
        provider.add("gtna.godforge.upgrade.tt.short.14", "GGEBE");
        provider.add("gtna.godforge.upgrade.tt.short.15", "TPTP");
        provider.add("gtna.godforge.upgrade.tt.short.16", "DoP");
        provider.add("gtna.godforge.upgrade.tt.short.17", "CNTI");
        provider.add("gtna.godforge.upgrade.tt.short.18", "EPEC");
        provider.add("gtna.godforge.upgrade.tt.short.19", "IMKG");
        provider.add("gtna.godforge.upgrade.tt.short.20", "NDPE");
        provider.add("gtna.godforge.upgrade.tt.short.21", "PoS");
        provider.add("gtna.godforge.upgrade.tt.short.22", "DoR");
        provider.add("gtna.godforge.upgrade.tt.short.23", "NGMS");
        provider.add("gtna.godforge.upgrade.tt.short.24", "SEDS");
        provider.add("gtna.godforge.upgrade.tt.short.25", "PA");
        provider.add("gtna.godforge.upgrade.tt.short.26", "CD");
        provider.add("gtna.godforge.upgrade.tt.short.27", "TSE");
        provider.add("gtna.godforge.upgrade.tt.short.28", "TBF");
        provider.add("gtna.godforge.upgrade.tt.short.29", "EE");
        provider.add("gtna.godforge.upgrade.tt.short.30", "END");
        provider.add("gtna.godforge.upgrade.tt.short.secret", "SECRET");
        provider.add("gtna.godforge.upgrade.lore.0",
                "The Forge of the Gods is an immensely powerful structure constructed around a stabilized neutron star – it is so advanced that its full capabilities are not yet understood. However, through continued use, one can slowly upgrade and expand the range of abilities of the Forge, and learn the power hidden in the most extreme parts of the universe: graviton shards. This esoteric material can only be found where conventional matter and degenerate neutronium crust matter on the surface of a neutron star meet. At this point in space, gravitons are far more common and irradiate this material mixture to create highly unstable graviton shards, which can be used to internally upgrade the Forge. While these shards cannot yet exist outside the extreme conditions of the Forge, with continued research and utilization it may be possible to eventually isolate and extract them outside the Forge – but for what purpose?");
        provider.add("gtna.godforge.upgrade.lore.1",
                "The first major upgrade of the Forge of the Gods has allowed for greater processing speeds as the heat increases, thanks to the gravitational warping effects of graviton shards. This is the first of many applications of the shards, which will be discovered through continuous use of the Forge.");
        provider.add("gtna.godforge.upgrade.lore.2",
                "Graviton shards warp the surface area of fuels used in the Forge, increasing efficiency as more material can be processed per unit of fuel. Graviton shards will prove crucial for further efficiency increases to offset the ever-increasing demands of the Forge.");
        provider.add("gtna.godforge.upgrade.lore.3",
                "Through use of graviton shards, the space within the Forge’s fuel chambers can be increased, allowing for greater quantities of fuel to be burned, thus reaching higher temperatures. Don’t forget to reserve fuel to keep the star at the centre of the Forge alive.");
        provider.add("gtna.godforge.upgrade.lore.4",
                "Graviton shards not only affect matter, but also energy: with high enough concentrations of stellar fuel, superconductivity is induced within the Forge purely through gravitational forces. What other properties could these Graviton shards hold?");
        provider.add("gtna.godforge.upgrade.lore.5",
                "As usage of the Forge continues, more data on graviton shards is gathered. It has been found that they can stabilize the outputs of the Forge, allowing for the direct extraction of molten material while it is still close to the heart of the star.");
        provider.add("gtna.godforge.upgrade.lore.6",
                "As stellar fuel consumption continues to increase the size and energy of the star, the amount of material that can be processed at once also increases. Graviton shards facilitate the manipulation of increased quantities of materials near the star in the core of the Forge.");
        provider.add("gtna.godforge.upgrade.lore.7",
                "As understanding of graviton shards continues to improve, better control over the materials they manipulate can be achieved. Graviton shards provide an alternative to electromagnetic containment of plasma using spacetime manipulation instead, allowing the Forge to directly output processed materials as plasma.");
        provider.add("gtna.godforge.upgrade.lore.8",
                "Adding graviton shards to the Forge’s internal energy storage allows for greater quantities of energy stored in a smaller area. By increasing energy density to relativistic levels, the Forge can be run more efficiently as the electrical potential continues to increase.");
        provider.add("gtna.godforge.upgrade.lore.9",
                "Simply adding more graviton shards to the fuel chamber continues to amplify the ability for the Forge to consume increased quantities of stellar fuel. It even benefits from graviton shards invested in different parts of the Forge entirely – it seems shards exhibit quantum entanglement-like properties.");
        provider.add("gtna.godforge.upgrade.lore.10",
                "Increasing the concentration of graviton shards near the material processing regions of the Forge warps spacetime so significantly that it manipulates materials from the causal future and past. This essentially doubles the material input capacity and processing capabilities.");
        provider.add("gtna.godforge.upgrade.lore.11",
                "Using large quantities of graviton shards creates regions of space so extreme that exotic forms of matter can exist with far greater stability than usual. Unfortunately, this region is so extreme that it is essentially spatially disconnected from the rest of the Forge, unable to utilize existing upgrades to the structure and its other modules.");
        provider.add("gtna.godforge.upgrade.lore.12",
                "Exposure to graviton-induced micro black holes can further compress stellar fuel, increasing its ability to fuel the star at the centre of the Forge through higher energy fusion reactions than usually possible in a natural star. As a result, greater heat is produced, increasing processing efficiency of the Forge.");
        provider.add("gtna.godforge.upgrade.lore.13",
                "Increasing the concentration of graviton shards in the fuel chamber begins to exhibit infinite fractal-like properties within finite space, further increasing processing capacity. Though this requires a commensurate increase in stellar fuel to ensure energy reaches matter deep within the chamber.");
        provider.add("gtna.godforge.upgrade.lore.14",
                "Utilising the unique energy-manipulating properties of graviton shards, electricity can be more efficiently utilised within the Forge. Guiding electrons with gravity rather than matter or electromagnetic forces results in less power loss and thus greater processing speeds.");
        provider.add("gtna.godforge.upgrade.lore.15",
                "Similar to the Quantum Force Transformer, the quantum-mechanical properties of graviton shards facilitate the ability for the Forge to complete a complex series of nuclear fusion processes in a single event by directly manipulating the subatomic particles of the materials themselves.");
        provider.add("gtna.godforge.upgrade.lore.16",
                "Another instance of the entanglement-like effects of graviton shards, the simple Power Forge module now also exhibits the improvements made to the Melting Core module of the Forge. This allows for greater efficiency in both processing and allocation of the precious few graviton shards that can be obtained.");
        provider.add("gtna.godforge.upgrade.lore.17",
                "Typical smelting techniques for exotic materials become too inefficient even at extreme temperatures. Graviton shards facilitate the tunnelling of unprecedented numbers of critically energized neutrinos for vastly improved heat transfer to the target material, one of the most efficient methods of transforming electrical energy into heat for materials.");
        provider.add("gtna.godforge.upgrade.lore.18",
                "Graviton shards can manipulate not just processing matter, but the star at the centre of the Forge itself. By rotating the star at relativistic speeds, the resulting pulsar bursts can impart more energy per unit of time than mere static exposure. This results in faster processing of larger quantities of materials.");
        provider.add("gtna.godforge.upgrade.lore.19",
                "Continual improvements to energy storage density using graviton shards improves both the efficiency of the Forge and improvements to heat utilisation for processing. Reaching the singularity threshold of energy has a twofold effect on processing efficiency: the gravitational effects can be used to manipulate the matter itself, while the micro-kugelblitzes paradoxically make their energy more available for use in the Forge.");
        provider.add("gtna.godforge.upgrade.lore.20",
                "Normally increasing heat indefinitely has extreme diminishing returns when processing materials, but graviton shards allow for other heating options than standard electrically generated heat. Using graviton shards, encasing the target material in extremely degenerate matter compresses it so greatly that it heats up beyond what would be typically possible in the Forge.");
        provider.add("gtna.godforge.upgrade.lore.21",
                "Using the entanglement-like properties of graviton shards, it is possible to utilize the increasingly extreme differences in spacetime between regions of the Forge to improve the processing capacity of the molten module. As space becomes more warped, more material can be moved closer to the star, increasing production capacity.");
        provider.add("gtna.godforge.upgrade.lore.22",
                "Returning to the first upgrade of the Forge with the myriad discoveries about graviton shards allows it to run much faster than previously possible. It is sometimes important to review the most basic of assumptions when working outside the known laws of physics, for the simplest facts may be the most powerful.");
        provider.add("gtna.godforge.upgrade.lore.23",
                "The stress of maintaining such a large structure around such a gravitationally dense object as a neutron star is alleviated through graviton shards. A sheath of gravitational-neutralising material is installed across the Forge to protect the more conventional machinery and only improves efficiency the larger the structure becomes.");
        provider.add("gtna.godforge.upgrade.lore.24",
                "Improvements in understanding of the gravitational containment effects of graviton shards allow the Forge to process and handle the most exotic of plasmas, including typically nanosecond-lived synthetic transactinide elements. It also extends their lifetime for external usage by stabilizing the atomic nucleus with small quantities of gravitons.");
        provider.add("gtna.godforge.upgrade.lore.25",
                "Further utilisation of the quantum entanglement-like properties of graviton shards allows the effects of other module upgrades to also apply to the exotic module. However, because of the extreme nature of spacetime within this module and the materials it handles, these benefits are reduced as per the inverse square law.");
        provider.add("gtna.godforge.upgrade.lore.26",
                "As additional rings are placed closer to the star at the centre of the Forge, the gravitational stress drastically increases on the structure. Graviton shards alleviate these stresses while also creating localized spacetime bridges to link the two rings and their modules’ respective upgrades.");
        provider.add("gtna.godforge.upgrade.lore.27",
                "A huge development in the capabilities of the Forge has been achieved with the use of large quantities of graviton shards – the ability to indefinitely feed the star with stellar fuel. While this has diminishing returns, the star can exist indefinitely despite the extremely accelerated energy expenditure from endless material processing.");
        provider.add("gtna.godforge.upgrade.lore.28",
                "The usage of graviton shards in electrical systems to create localised miniature energy wormholes has allowed for such efficient power transfer that effectively unlimited electricity may be utilized by the Forge. More power means faster processing, quicker material movement, and better utilization of graviton shard related upgrades.");
        provider.add("gtna.godforge.upgrade.lore.29",
                "Further enrichment of the extreme spaces within the Plasma Fabricator & Exoticizer allows for the production of the most exotic plasmas beyond merely periodic elements and facilitates the creation of completely new kinds of subatomic particles, resulting in the creation of magmatter, a form of matter made entirely of magnetic monopoles with density and stability billions of times that of conventional bosonic matter.");
        provider.add("gtna.godforge.upgrade.lore.30",
                "With the construction of the third and final ring, total mastery of the Forge of the Gods has been achieved and it is now possible to quantize and extract graviton shards for use outside the Forge in powerful new technological endeavours. It is with this development you realise that the completion of the Forge was not the end goal, but merely a stepping stone to universal transcendence.");
        provider.add("gtna.godforge.upgrade.text.0",
                "Unlocks the base functionality of the Forge of the Gods, meaning 8 module slots, 1 ring, the Helioflare Power Forge module, 2 billion EU/t processing voltage and 15,000K heat bonus cap.");
        provider.add("gtna.godforge.upgrade.text.1",
                "Unlocks a recipe time reduction multiplier based on the current heat the multi is running at. This bonus is calculated via following formula: Multiplier = 1 / (Heat^0.01)");
        provider.add("gtna.godforge.upgrade.text.2",
                "Increases fuel efficiency by multiplying the actual fuel consumption by 0.8");
        provider.add("gtna.godforge.upgrade.text.3", "Multiplies the maximum fuel consumption by 1.2");
        provider.add("gtna.godforge.upgrade.text.4",
                "Increases the base processing voltage of all modules by: Stellar Fuel Units/sec * 10^8 EU/t");
        provider.add("gtna.godforge.upgrade.text.5", "Unlocks the Helioflux Melting Core module.");
        provider.add("gtna.godforge.upgrade.text.6",
                "Unlocks a multiplier to maximum parallel based on fuel consumption rate. This bonus is calculated via this formula: Multiplier = 1 + (Stellar Fuel Units/sec) / 15");
        provider.add("gtna.godforge.upgrade.text.7",
                "Unlocks the Heliothermal Plasma Fabricator module and basic element -> plasma processing (1 step plasmas, T3 fusion maximum).");
        provider.add("gtna.godforge.upgrade.text.8",
                "Unlocks a configuration window for maximum battery size and increases the limit to max int. Furthermore, an energy discount multiplier is unlocked that scales with battery size (capped to 0.05, or 5%%). The discount is calculated as follows: Discount = (1 - 1.05^(-0.05 * Max Battery Capacity)) / 20");
        provider.add("gtna.godforge.upgrade.text.9",
                "Increases maximum fuel consumption by 1 Stellar Fuel Unit/sec for every purchased upgrade.");
        provider.add("gtna.godforge.upgrade.text.10", "Adds a x2 multiplier to maximum parallel.");
        provider.add("gtna.godforge.upgrade.text.11",
                "Unlocks the Heliofusion Exoticizer module and quark gluon plasma creation. At this point this module is not affected by any other multipliers or bonuses from other upgrades.");
        provider.add("gtna.godforge.upgrade.text.12",
                "Improves the fuel consumption -> heat conversion formula. Improved formula: Power Forge Heat = log_1.12(Stellar Fuel Units/sec) * 1000 + 12601, Melting Core Heat = log1.18(Stellar Fuel Units/sec) * 1000 + 12601");
        provider.add("gtna.godforge.upgrade.text.13",
                "Improves the formula of SA to: Multiplier = 1 + (Stellar Fuel Units/sec) / 5");
        provider.add("gtna.godforge.upgrade.text.14",
                "Allows the OC factor to scale with current heat. Power Forges and Melting Cores gain a static OC factor of 2.15. Plasma fabricator OC factor = 4 - 25000 / Heat ");
        provider.add("gtna.godforge.upgrade.text.15",
                "Allows the Heliothermal Plasma Fabricator to process multi step plasmas. Tier restriction still applies.");
        provider.add("gtna.godforge.upgrade.text.16",
                "Allows the Helioflare Power Forge to receive the full benefits of the Helioflux Melting Core upgrade path.");
        provider.add("gtna.godforge.upgrade.text.17", "Increases the cap of EBF heat bonuses to 30,000K.");
        provider.add("gtna.godforge.upgrade.text.18",
                "Unlocks a multiplier to maximum parallel based on current heat. This bonus is calculated via this formula: Multiplier = 1 + Heat / 15000");
        provider.add("gtna.godforge.upgrade.text.19",
                "Improves the EBF energy reduction heat bonus from 5%% to 8%% and adds an energy discount based on the fill level of the internal battery. This bonus is calculated via the formula: Discount = (Current fill level / Max Capacity - 0.5)^2 * (-0.6) + 0.15, multiplied by 2/3 for modules other than the Plasma Fabricator");
        provider.add("gtna.godforge.upgrade.text.20",
                "EBF heat bonuses are granted above 30,000K, but the heat value used in heat bonus calculations is determined by this formula: Power Forge Heat = 30000 + (Current Heat - 30000)^0.85, Melting Core Heat = 30000 + (Current Heat - 30000)^0.8");
        provider.add("gtna.godforge.upgrade.text.21",
                "Unlocks a multiplier to maximum parallel based on total amount of purchased upgrades. This bonus is calculated via this formula: Multiplier = 1 + Upgrade Amount / 5");
        provider.add("gtna.godforge.upgrade.text.22",
                "Improves IGCC based on current maximum parallel. Improved Formula: Multiplier = (1 / Heat^0.01) / (Parallel^0.02)");
        provider.add("gtna.godforge.upgrade.text.23",
                "Multiplies maximum processing voltage by 4 per active ring, applies after other bonuses.");
        provider.add("gtna.godforge.upgrade.text.24",
                "Allows the Heliothermal Plasma Fabricator to process up to T5 plasmas.");
        provider.add("gtna.godforge.upgrade.text.25",
                "Allows the Heliofusion Exoticizer to be affected by other upgrade benefits, but those benefits are square rooted first. The overclock bonus is adjusted via the following formula: OC Factor = 2 + (Base OC Factor - 2)^2");
        provider.add("gtna.godforge.upgrade.text.26",
                "Allows construction of the second ring and adds 4 module slots.");
        provider.add("gtna.godforge.upgrade.text.27",
                "Uncaps maximum fuel consumption, but fuel consumption used in bonus calculations scales according to this formula: Actual FC = Current Max FC + (Current FC - Current Max FC)^0.4, where FC refers to fuel consumption and max FC refers to the max fuel consumption without this upgrade. Note that fuel consumption cannot exceed 2^31 for technical reasons.");
        provider.add("gtna.godforge.upgrade.text.28",
                "Uncaps maximum processing voltage. Voltage can be set in each module's GUI.");
        provider.add("gtna.godforge.upgrade.text.29",
                "Unlocks Magmatter production in the Heliofusion Exoticizer and creation of exotic plasmas in the Heliothermal Plasma Fabricator.");
        provider.add("gtna.godforge.upgrade.text.30",
                "Allows construction of the third ring, adds 4 module slots and unlocks Graviton Shard ejection & injection.");
        provider.add("gtna.godforge.button.fuelconfig.tooltip", "Fuel Configuration Menu");
        provider.add("gtna.godforge.button.upgradetree.tooltip", "Path of Celestial Transcendence");
        provider.add("gtna.godforge.button.furnacemode.tooltip.01", "Blast Mode");
        provider.add("gtna.godforge.button.furnacemode.tooltip.02", "Furnace Mode");
        provider.add("gtna.godforge.button.magmattermode.tooltip.01", "Quark-Gluon Plasma Mode");
        provider.add("gtna.godforge.button.magmattermode.tooltip.02", "Magmatter Mode");
        provider.add("gtna.godforge.button.magmattermode.tooltip.03", "Magmatter Mode locked, missing upgrade");
        provider.add("gtna.godforge.button.battery.tooltip.01", "Toggle Battery Charging");
        provider.add("gtna.godforge.button.battery.tooltip.02", "Right click to open configuration menu (if unlocked)");
        provider.add("gtna.godforge.button.voltageconfig.tooltip.01", "Open voltage config");
        provider.add("gtna.godforge.button.voltageconfig.tooltip.02",
                "Voltage config locked, requires The Boundless Flow (upgrade)");
        provider.add("gtna.godforge.button.structurecheck.tooltip", "Refresh module connection status");
        provider.add("gtna.godforge.button.milestones.tooltip", "Milestone Overview");
        provider.add("gtna.godforge.button.materialrequirements.tooltip", "Upgrade needs additional materials");
        provider.add("gtna.godforge.button.materialrequirementsmet.tooltip", "All materials supplied");
        provider.add("gtna.godforge.button.materialrequirements.tooltip.clickhere",
                "Click to open material insertion window");
        provider.add("gtna.godforge.button.ejection.tooltip", "Toggle Graviton Shard Ejection");
        provider.add("gtna.godforge.button.formatting.tooltip", "Toggle Number Formatting");
        provider.add("gtna.godforge.button.exoticinputs.tooltip", "Click to display expected inputs");
        provider.add("gtna.godforge.button.possibleexoticinputs.tooltip", "Click to display all possible inputs");
        provider.add("gtna.godforge.button.reciperefresh.tooltip", "Click to reset recipe");
        provider.add("gtna.godforge.button.refreshtimer.tooltip", "Reset ready in");
        provider.add("gtna.godforge.button.seconds", "Seconds");
        provider.add("gtna.godforge.button.thanks.tooltip", "List of Contributors");
        provider.add("gtna.godforge.button.color.tooltip", "Cosmetics Menu");
        provider.add("gtna.godforge.button.statistics.tooltip", "Stats Overview");
        provider.add("gtna.godforge.text.tooltip.heat", "Heat value used for checking if a recipe can run");
        provider.add("gtna.godforge.text.tooltip.effectiveheat", "Heat value used for calculating bonuses");
        provider.add("gtna.godforge.text.tooltip.parallel", "Maximum parallel amount");
        provider.add("gtna.godforge.text.tooltip.speedbonus", "Multiplier for base recipe time, making it shorter");
        provider.add("gtna.godforge.text.tooltip.energydiscount", "Multiplier for base energy usage, reducing it");
        provider.add("gtna.godforge.text.tooltip.ocdivisor",
                "Divisor for recipe time reduction per overclock (does not affect perfect OCs)");
        provider.add("gtna.godforge.text.tooltip.processingvoltage", "Base processing voltage for recipes");
        provider.add("gtna.godforge.text.tooltip.factorpreview", "Enter fuel factor to simulate calculations with");
        provider.add("gtna.godforge.text.tooltip.applysimulationchanges", "Simulate new values");
        provider.add("gtna.godforge.text.tooltip.voltageadjustment",
                "Because of overflow concerns, actual voltage follows this formula:");
        provider.add("gtna.godforge.text.tooltip.voltageadjustment.1",
                "Voltage = Min(Selected Voltage, 2^63 / Max Parallel)");
        provider.add("gtna.godforge.gui.parallel", "Parallel");
        provider.add("gtna.godforge.gui.batch", "Batch Size");
        provider.add("gtna.godforge.gui.fuelconsumption", "Stellar Fuel Consumption Factor");
        provider.add("gtna.godforge.gui.fuelinfo.0",
                "The Stellar Fuel Consumption Factor is the main determining factor in calculating the total stellar fuel consumption per second. Each fuel type has different scaling, which is as follows:");
        provider.add("gtna.godforge.gui.fuelinfo.1", "Dimensionally Transcendent Residue: factor*300*1.15^factor");
        provider.add("gtna.godforge.gui.fuelinfo.2", "Condensed Raw Stellar Plasma Mixture: factor*2*1.08^factor");
        provider.add("gtna.godforge.gui.fuelinfo.3", "Magnetohydrodynamically Constrained Star Matter: factor/25");
        provider.add("gtna.godforge.gui.fuelinfo.4",
                "This factor also determines the base heat of the multiblock: Heat=log_1.5(factor)*1000+12601");
        provider.add("gtna.godforge.gui.fuelinfo.5",
                "Upgrades can influence these formulas, the changes are listed in the respective upgrades' descriptions.");
        provider.add("gtna.godforge.gui.fueltype", "Click to Select Fuel Type");
        provider.add("gtna.godforge.gui.fuelusage", "Fuel Usage");
        provider.add("gtna.godforge.gui.plasmamultistep", "Multi-Step plasma: %s");
        provider.add("gtna.godforge.gui.plasmarecipetier", "Fusion Tier: %s");
        provider.add("gtna.godforge.gui.storedfuel", "Stored fuel amount:");
        provider.add("gtna.godforge.gui.storedstartupfuel", "Star Fuel amount:");
        provider.add("gtna.godforge.gui.batteryinfo", "Set battery size");
        provider.add("gtna.godforge.gui.shardcost", "Graviton Shard cost:");
        provider.add("gtna.godforge.gui.availableshards", "Available Graviton Shards:");
        provider.add("gtna.godforge.gui.modulestatus", "Status:");
        provider.add("gtna.godforge.gui.modulestatus.true", "Connected");
        provider.add("gtna.godforge.gui.modulestatus.false", "Disconnected");
        provider.add("gtna.godforge.gui.voltageinfo", "Voltage Per Parallel");
        provider.add("gtna.godforge.gui.totalprogress", "Total Progress");
        provider.add("gtna.godforge.gui.milestoneprogress", "Current Milestone Level");
        provider.add("gtna.godforge.gui.progress", "Next Milestone at");
        provider.add("gtna.godforge.gui.milestonecomplete", "Milestone Complete");
        provider.add("gtna.godforge.gui.milestoneinfo", "View Milestone Progress");
        provider.add("gtna.godforge.gui.inversionactive", "Inversion Active");
        provider.add("gtna.godforge.gui.expectedinputs", "Expected Inputs");
        provider.add("gtna.godforge.gui.possibleinputsqgp", "Possible Input Materials for QGP");
        provider.add("gtna.godforge.gui.possibleinputsmagmatter", "Possible Input Materials for Magmatter");
        provider.add("gtna.godforge.gui.powermilestone", "Charge");
        provider.add("gtna.godforge.gui.recipemilestone", "Conversion");
        provider.add("gtna.godforge.gui.fuelmilestone", "Catalyst");
        provider.add("gtna.godforge.gui.purchasablemilestone", "Composition");
        provider.add("gtna.godforge.gui.power", "EU Consumed");
        provider.add("gtna.godforge.gui.recipes", "Recipes Processed");
        provider.add("gtna.godforge.gui.fuelconsumed", "Fuel Units Consumed");
        provider.add("gtna.godforge.gui.extensions", "Extensions Built");
        provider.add("gtna.godforge.gui.shardgain", "Graviton Shards gained");
        provider.add("gtna.godforge.gui.payUpgradeCosts", "Pay Upgrade Cost");
        provider.add("gtna.godforge.gui.consumeUpgradeMats", "Click to consume upgrade materials");
        provider.add("gtna.godforge.gui.clickhere", "Confused? Click here for some general info");
        provider.add("gtna.godforge.gui.introduction", "§NIntroduction");
        provider.add("gtna.godforge.gui.introductioninfotext",
                "There's a lot going on in the Forge of the Gods, which can be quite confusing at first. This menu aims to explain everything that is happening and all the capabilities/mechanics of the forge.");
        provider.add("gtna.godforge.gui.tableofcontents", "§NTable of Contents");
        provider.add("gtna.godforge.gui.fuel", "Fuel");
        provider.add("gtna.godforge.gui.modules", "Modules");
        provider.add("gtna.godforge.gui.upgrades", "Upgrades");
        provider.add("gtna.godforge.gui.milestones", "Milestones");
        provider.add("gtna.godforge.gui.inversion", "Inversion");
        provider.add("gtna.godforge.gui.fuelinfotext.1",
                "Once the structure of the Forge is built and the multiblock is formed, just simply turning it on is not sufficient to make it functional. The Forge must be supplied with a certain amount of §bStar Fuel §6(the item) to actually boot up.");
        provider.add("gtna.godforge.gui.fuelinfotext.2",
                "The amount of Star Fuel needed depends on the current fuel consumption factor, which can be set in the fuel configuration menu. By default the maximum is 5, but it can be increased later on with upgrades. Star Fuel scaling is as follows:");
        provider.add("gtna.godforge.gui.fuelinfotext.3", "factor*25*1.2^factor");
        provider.add("gtna.godforge.gui.fuelinfotext.4",
                "Star Fuel can be supplied via an input bus, it gets consumed periodically and stored internally. Once there is enough Star Fuel stored in the multi, it turns on for real (allowing modules to connect) and converts the consumed Star Fuel into stored §bStellar Fuel§6.");
        provider.add("gtna.godforge.gui.fuelinfotext.5",
                "From this point onwards, the Forge must be fueled via one of the liquid fuels (type can be selected in the fuel config menu). If there isn't enough of the selected fuel present in the input hatch, the stored fuel amount will decrease and if it reaches 0, the Forge enters the previous 'off' state where modules disconnect and it has to be supplied with Star Fuel again.");
        provider.add("gtna.godforge.gui.fuelinfotext.6",
                "The amount of internally stored Stellar Fuel (liquid) can be increased by turning on §bBattery Charging§6, this will cause the fuel usage to double, but half of it will be stored in the internal battery.");
        provider.add("gtna.godforge.gui.moduleinfotext.1",
                "There are 4 types of modules that can be used in the Forge, the Helioflare Power Forge, Helioflux Melting Core, Heliothermal Plasma Fabricator and Heliofusion Exoticizer. These modules are separate multiblocks that have to be built into the Forge's structure at their designated spots.");
        provider.add("gtna.godforge.gui.moduleinfotext.2",
                "Once built, these modules have to connect to the Forge, which happens automatically if all requirements for the respective module are met. Alternatively, there is a button to refresh their status without waiting for the timer. Each of these modules has its specialized functionality & requirements and is affected differently by certain upgrades.");
        provider.add("gtna.godforge.gui.moduleinfotext.forge.1", "Helioflare Power Forge");
        provider.add("gtna.godforge.gui.moduleinfotext.forge.2",
                "The first unlocked module, simply put is a blast furnace even more powerful than the Exothermic Hearth. Additionally, this module has a §bFurnace Mode§6, turning it into a hyper powerful Multi Smelter. This module is unlocked by default and has §b1024§6 base parallel.");
        provider.add("gtna.godforge.gui.moduleinfotext.core.1", "Helioflux Melting Core");
        provider.add("gtna.godforge.gui.moduleinfotext.core.2",
                "The second unlocked module, which also processes blast furnace recipes but with a twist; the outputs are ejected in §bMolten form§6 instead of ingots. If an output does not have a molten form, it will output its regular form. This module has to be unlocked by an upgrade to function and has §b512§6 base parallel.");
        provider.add("gtna.godforge.gui.moduleinfotext.fab.1", "Heliothermal Plasma Fabricator");
        provider.add("gtna.godforge.gui.moduleinfotext.fab.2",
                "The third unlocked module, which possesses a unique recipemap featuring direct material to plasma conversion recipes. These recipes are grouped by two properties, §bFusion Tier§6 and §bSteps Required§6, limiting which recipes can be processed before their respective upgrades are unlocked. Unlike regular fusion, these recipes produce the plasma of the input material. This module has §b512§6 base parallel.");
        provider.add("gtna.godforge.gui.moduleinfotext.exotic.1", "Heliofusion Exoticizer");
        provider.add("gtna.godforge.gui.moduleinfotext.exotic.2",
                "The fourth and final unlocked module, capable of producing §bQuark Gluon Plasma§6 and later on §bMagmatter§6. This module has unique automation challenges for both materials, so it is recommended to have two of these, as they have to be locked to either one of the materials.");
        provider.add("gtna.godforge.gui.moduleinfotext.exotic.3",
                "The common rule for both modes' automation challenges is as follows: the module outputs materials at the start of a recipe cycle and waits for the correct inputs to arrive before starting the actual processing of the output material.");
        provider.add("gtna.godforge.gui.moduleinfotext.exotic.4",
                "If producing §bQuark Gluon Plasma§6, the module outputs up to 7 different fluids/dusts with amounts between 1-64 and 1-7 respectively, and their corresponding plasmas and amounts have to be returned in order for the recipe to process. For each L of fluid, a bucket of plasma and for each dust 9 ingots worth of plasma must be returned for the recipe to work.");
        provider.add("gtna.godforge.gui.moduleinfotext.exotic.5",
                "If §bMagmatter Mode§6 is active, the automation challenge changes. Now the module outputs 1-50L of §bTachyon Rich Temporal Fluid§6, 51-100L of §bSpatially Enlarged Fluid§6 and one dust of a high tier material. The challenge is to return both the Tachyon Rich and Spatially Enlarged Fluids, plus as much plasma of the dust's material (in ingots) as the difference between the amounts of Spatially Enlarged and Tachyon Rich Fluid. Once all of these have been returned in the correct amounts, the recipe will start to process and output Magmatter.");
        provider.add("gtna.godforge.gui.moduleinfotext.exotic.6", "This module has §b64§6 base parallel.");
        provider.add("gtna.godforge.gui.upgradeinfotext.1",
                "Upgrades are the heart and soul of the Forge, they unlock most of its functionality and processing power. The §bUpgrade Tree§6 can be accessed via its button on the main GUI, and each upgrade node can be clicked for more information on its effects and unlock requirements.");
        provider.add("gtna.godforge.gui.upgradeinfotext.2",
                "In general, each upgrade can only be unlocked if the prior one is unlocked and there are enough available §bGraviton Shards§6. One exception to this is the first upgrade, which has no prior upgrade. Some upgrades also have extra material costs, which are denoted next to the unlock button if applicable.");
        provider.add("gtna.godforge.gui.upgradeinfotext.3",
                "If an upgrade has more than one connected prior upgrade, then there are two options. The upgrade requires either:");
        provider.add("gtna.godforge.gui.upgradeinfotext.4",
                "- All prior upgrades (§4Red§a connections)\n- At least one prior upgrade (§9Blue§a connections)");
        provider.add("gtna.godforge.gui.upgradeinfotext.5",
                "Upgrades can be refunded by pressing the §bRespec§6 button, but this only works if ALL connected later upgrades are not active/unlocked.");
        provider.add("gtna.godforge.gui.upgradeinfotext.6",
                "The block of upgrades following the unlock of the Heliofusion Exoticizer module are special, as they are what is considered §bThe Split§6. As the name suggests, only one path out of the three may be chosen at first, and the others will be locked. Each path has specialized buffs that are primarily targeted towards a specific module, and thus affect other module types with reduced effect (unless stated otherwise). The amount of unlockable paths depends on the §bAmount of Rings§6 the Forge has, which in turn is limited by later upgrades.");
        provider.add("gtna.godforge.gui.milestoneinfotext.1",
                "Milestones are essential for upgrading the Forge, as they are the source of §bGraviton Shards§6, the main currency needed for unlocking upgrades. In essence, milestones are just what their name suggests, thresholds that when reached, grant Graviton Shards.");
        provider.add("gtna.godforge.gui.milestoneinfotext.2",
                "There are four types of milestones, Charge, Conversion, Catalyst and Composition, each referring to a stat of the Forge. Each milestone has §bseven§6 tiers, each being harder to reach than the last, but also granting more Graviton Shards. The first tier grants 1 Shard, the second 2, the third 3 and so on.");
        provider.add("gtna.godforge.gui.milestoneinfotext.3",
                "The §bCharge§6 milestone scales off total power consumption of all modules combined, the first tier being unlocked at §b1e15§6 EU consumed, and each subsequent milestone scaling by §b9x§6.");
        provider.add("gtna.godforge.gui.milestoneinfotext.4",
                "The §bConversion§6 milestone scales off total recipes processed across all modules (excluding the Helioflare Power Forge's furnace mode) and its first tier is unlocked at §b10M§6 processed recipes. Following tiers scale by §b4x§6.");
        provider.add("gtna.godforge.gui.milestoneinfotext.5",
                "The §bCatalyst§6 milestone is based on the Forge's fuel consumption, counted in Stellar Fuel units (the number entered in the fuel config menu). Reaching the first tier requires §b10,000§6 fuel units to be consumed, and each tier above scales by §b3x§6.");
        provider.add("gtna.godforge.gui.milestoneinfotext.6",
                "Last but not least, the §bComposition§6 milestone works a bit differently, as it scales off the Forge's structure. Milestone levels are granted for each unique type of module present in the structure (Heliofusion Exoticizer modules on Quark Gluon and Magmatter Modes count as unique), and for each additional ring built.");
        provider.add("gtna.godforge.gui.milestoneinfotext.7",
                "Your research suggests that something strange might happen if all milestones reach their final tier... Make sure to check back!");
        provider.add("gtna.godforge.gui.inversioninfotext.1",
                "Once all milestones of the Forge reach §bTier 7§6, inversion activates. This uncaps the maximum tier of all milestones and allows it to scale §binfinitely§6.");
        provider.add("gtna.godforge.gui.inversioninfotext.2",
                "The scaling of each milestone changes from exponential to linear, but the granted Graviton Shard amount keeps increasing. The amount of progress needed for each subsequent milestone is as much as needed for the §b7th tier§6 of each milestone.");
        provider.add("gtna.godforge.gui.inversioninfotext.3",
                "The Composition milestone is once again an exception, as that continues to scale by 1 each tier, with its own formula for calculating progress. Each module type is given a value, ranging from §b1§6 for the Helioflare Power Forge to §b5§6 for the Heliofusion Exoticizer in Magmatter Mode, then the amount of each module present is subtracted by 1 and multiplied by its value. These values are added up and divided by 5, this is the final milestone tier on top of the base 7.");
        provider.add("gtna.godforge.gui.contributors", "Contributors");
        provider.add("gtna.godforge.gui.lead", "Project Lead");
        provider.add("gtna.godforge.gui.cloud", "GDCloud");
        provider.add("gtna.godforge.gui.programming", "Programming");
        provider.add("gtna.godforge.gui.teg", "TheEpicGamer");
        provider.add("gtna.godforge.gui.serenibyss", "§dSereni§5byss");
        provider.add("gtna.godforge.gui.textures", "Textures & Structure");
        provider.add("gtna.godforge.gui.ant", "Ant");
        provider.add("gtna.godforge.gui.lore", "Loremaster");
        provider.add("gtna.godforge.gui.deleno", "Deleno");
        provider.add("gtna.godforge.gui.rendering", "Rendering Wizard");
        provider.add("gtna.godforge.gui.bucket", "BucketBrigade");
        provider.add("gtna.godforge.gui.playtesting", "Playtesting");
        provider.add("gtna.godforge.gui.misi", "Misi");
        provider.add("gtna.godforge.gui.thanks",
                "A huge thank you to these incredible people for helping to make this a reality! -Cloud");
        provider.add("gtna.godforge.gui.modulestats", "Module Statistics");
        provider.add("gtna.godforge.gui.powerforge", "Power Forge");
        provider.add("gtna.godforge.gui.meltingcore", "Melting Core");
        provider.add("gtna.godforge.gui.plasmafab", "Plasma Fabricator");
        provider.add("gtna.godforge.gui.exoticizer", "Exoticizer");
        provider.add("gtna.godforge.gui.heat", "Heat");
        provider.add("gtna.godforge.gui.effectiveheat", "Effective Heat");
        provider.add("gtna.godforge.gui.speedbonus", "Speed Bonus");
        provider.add("gtna.godforge.gui.energydiscount", "Energy Discount");
        provider.add("gtna.godforge.gui.ocdivisor", "OC Divisor");
        provider.add("gtna.godforge.gui.processingvoltage", "Processing Voltage");
        provider.add("gtna.godforge.gui.factorpreview", "Preview Fuel Factor:");
        provider.add("gtna.godforge.gui.clickstat", "Click to view value breakdown");
        provider.add("gtna.godforge.gui.hint.0",
                "1 - Classic Hatches or Transcendentally Amplified Magnetic Confinement Casing");
        provider.add("gtna.godforge.gui.hint.1",
                "2 - Module Controllers or Singularity Reinforced Stellar Shielding Casing");
        provider.add("gtna.godforge.cosmetics.header", "Star Cosmetics");
        provider.add("gtna.godforge.cosmetics.color", "Color");
        provider.add("gtna.godforge.cosmetics.color.red", "Red");
        provider.add("gtna.godforge.cosmetics.color.green", "Green");
        provider.add("gtna.godforge.cosmetics.color.blue", "Blue");
        provider.add("gtna.godforge.cosmetics.color.hue", "H");
        provider.add("gtna.godforge.cosmetics.color.saturation", "S");
        provider.add("gtna.godforge.cosmetics.color.value", "V");
        provider.add("gtna.godforge.cosmetics.color.gamma", "Gamma");
        provider.add("gtna.godforge.cosmetics.color.rgb", "RGB");
        provider.add("gtna.godforge.cosmetics.color.rgb_colored", "§cR§aG§9B");
        provider.add("gtna.godforge.cosmetics.color.hsv", "HSV");
        provider.add("gtna.godforge.cosmetics.color.hsv_colored", "§dH§6S§bV");
        provider.add("gtna.godforge.cosmetics.color.hex", "Hex:");
        provider.add("gtna.godforge.cosmetics.selectcolor.tooltip.1", "Left click to select this Star Color");
        provider.add("gtna.godforge.cosmetics.selectcolor.tooltip.2",
                "Shift-Left click to edit this Star Color (must be a custom color)");
        provider.add("gtna.godforge.cosmetics.starcolor", "Custom Star Color");
        provider.add("gtna.godforge.cosmetics.customstarcolor", "Custom...");
        provider.add("gtna.godforge.cosmetics.misc", "Miscellaneous");
        provider.add("gtna.godforge.cosmetics.spin", "Spin");
        provider.add("gtna.godforge.cosmetics.size", "Size");
        provider.add("gtna.godforge.cosmetics.animations", "Animations");
        provider.add("gtna.godforge.cosmetics.animations.tooltip", "May take a moment to refresh when toggled");
        provider.add("gtna.godforge.cosmetics.cyclespeed", "Cycle speed between colors");
        provider.add("gtna.godforge.cosmetics.onlyintegers", "Accepts Integers");
        provider.add("gtna.godforge.cosmetics.onlydecimals", "Accepts Decimals");
        provider.add("gtna.godforge.cosmetics.starcolorname", "Star Color Name:");
        provider.add("gtna.godforge.cosmetics.starcolorname.tooltip.1",
                "Set the name for this Star Color (max 15 chars)");
        provider.add("gtna.godforge.cosmetics.starcolorname.tooltip.2",
                "Must be unique! Will have a number appended otherwise");
        provider.add("gtna.godforge.cosmetics.colorlist.tooltip.1", "Left click to select this Star Color");
        provider.add("gtna.godforge.cosmetics.colorlist.tooltip.2",
                "Right click to remove this Star Color from the list");
        provider.add("gtna.godforge.cosmetics.applycolor", "Apply");
        provider.add("gtna.godforge.cosmetics.applycolor.tooltip", "Apply color to selected Star Color");
        provider.add("gtna.godforge.cosmetics.addcolor", "Add");
        provider.add("gtna.godforge.cosmetics.addcolor.tooltip", "Add to Star Color List");
        provider.add("gtna.godforge.cosmetics.resetcolor", "Reset");
        provider.add("gtna.godforge.cosmetics.resetcolor.tooltip", "Reset Current Color");
        provider.add("gtna.godforge.cosmetics.savecolors", "Save");
        provider.add("gtna.godforge.cosmetics.savecolors.tooltip", "Save this Star Color");
        provider.add("gtna.godforge.cosmetics.deletecolors", "Delete");
        provider.add("gtna.godforge.cosmetics.deletecolors.tooltip", "Delete this Star Color");
        provider.add("gtna.godforge.cosmetics.importcolors", "Import");
        provider.add("gtna.godforge.cosmetics.importcolors.tooltip", "Import a Star Color from text");
        provider.add("gtna.godforge.cosmetics.exportcolors", "Export");
        provider.add("gtna.godforge.cosmetics.exportcolors.tooltip", "Copy exported Star Color to clipboard");
        provider.add("gtna.godforge.cosmetics.exportcolors.message", "Copied exported Star Color to clipboard");
        provider.add("gtna.godforge.cosmetics.exportcolors.failed", "Could not copy exported Star Color to clipboard");
        provider.add("gtna.godforge.cosmetics.importer.import", "Import Star Color");
        provider.add("gtna.godforge.cosmetics.importer.error", "Invalid Star Color");
        provider.add("gtna.godforge.cosmetics.importer.valid", "Valid Star Color");
        provider.add("gtna.godforge.cosmetics.importer.apply", "Apply");
        provider.add("gtna.godforge.cosmetics.importer.apply.tooltip", "Apply imported Star Color to color editor");
        provider.add("gtna.godforge.cosmetics.importer.reset", "Reset");
        provider.add("gtna.godforge.cosmetics.importer.reset.tooltip", "Reset imported Star Color");
        provider.add("gtna.godforge.star_color.preset.default", "Default");
        provider.add("gtna.godforge.star_color.preset.rainbow", "Rainbow");
        provider.add("gtna.godforge.star_color.preset.clouds_pick", "Cloud's Pick");
        provider.add("gtna.godforge.star_color.preset.mayas_pick", "Maya's Pick");
    }
}
