package com.raishxn.gtna.common.data.material;

import com.gregtechceu.gtceu.api.data.chemical.material.Material;

import com.raishxn.gtna.GTNACORE;

import static com.gregtechceu.gtceu.api.data.chemical.material.info.MaterialFlags.*;
import static com.raishxn.gtna.common.data.GTNAMaterials.*;

/**
 * Forge of Gods fuels and products with the GTNH names and formulas ({@code MaterialsInit}, GT5-Unofficial
 * a3e1e112). Acquisition recipes come with the progression phase; no autogenerated processing.
 */
public final class GodforgeMaterials {

    private GodforgeMaterials() {}

    /** GTCEu first, then GTNA, by the plain material name used in {@code GodforgePlasmaTable}. */
    public static Material material(String name) {
        var manager = com.gregtechceu.gtceu.api.GTCEuAPI.materialManager;
        Material material = manager.getMaterial("gtceu:" + name);
        if (material == null || material.isNull()) material = manager.getMaterial(GTNACORE.MOD_ID + ":" + name);
        return material == null || material.isNull() ? null : material;
    }

    /** Gives every Plasma Module material a plasma fluid, as GTNH has for all of them. */
    public static void addPlasmas() {
        for (var entry : com.raishxn.gtna.api.machine.feature.godforge.GodforgePlasmaTable.ENTRIES) {
            Material material = material(entry.material());
            if (material == null) continue;
            var key = com.gregtechceu.gtceu.api.fluids.store.FluidStorageKeys.PLASMA;
            var plasma = new com.gregtechceu.gtceu.api.fluids.FluidBuilder()
                    .state(com.gregtechceu.gtceu.api.fluids.FluidState.PLASMA);
            var fluid = material
                    .getProperty(com.gregtechceu.gtceu.api.data.chemical.material.properties.PropertyKey.FLUID);
            if (fluid == null) {
                material.setProperty(com.gregtechceu.gtceu.api.data.chemical.material.properties.PropertyKey.FLUID,
                        new com.gregtechceu.gtceu.api.data.chemical.material.properties.FluidProperty(key, plasma));
            } else if (fluid.getQueuedBuilder(key) == null && fluid.get(key) == null) {
                fluid.enqueueRegistration(key, plasma);
            }
        }
    }

    public static void init() {
        DimensionallyTranscendentResidue = new Material.Builder(GTNACORE.id("dimensionally_transcendent_residue"))
                .langValue("Dimensionally Transcendent Residue")
                .liquid(new com.gregtechceu.gtceu.api.fluids.FluidBuilder().temperature(0).customStill())
                .color(0x000000)
                .flags(DISABLE_DECOMPOSITION, DISABLE_MATERIAL_RECIPES).buildAndRegister().setFormula("✨-∅");
        MagnetohydrodynamicallyConstrainedStarMatter = new Material.Builder(
                GTNACORE.id("magnetohydrodynamically_constrained_star_matter"))
                .langValue("Magnetohydrodynamically Constrained Star Matter").ingot()
                .liquid(new com.gregtechceu.gtceu.api.fluids.FluidBuilder().temperature(0).customStill())
                .color(0xffffff).iconSet(GodforgeIconSets.MHDCSM).flags(DISABLE_DECOMPOSITION, DISABLE_MATERIAL_RECIPES)
                .buildAndRegister();
        MagMatter = new Material.Builder(GTNACORE.id("magmatter")).langValue("Magmatter").ingot()
                .liquid(new com.gregtechceu.gtceu.api.fluids.FluidBuilder().temperature(0).customStill())
                .color(0xffffff).iconSet(GodforgeIconSets.MAGMATTER)
                .flags(DISABLE_DECOMPOSITION, DISABLE_MATERIAL_RECIPES)
                .buildAndRegister().setFormula("M⎋");
        QuarkGluonPlasma = new Material.Builder(GTNACORE.id("quark_gluon_plasma"))
                .langValue("Degenerate Quark Gluon Plasma")
                .liquid(new com.gregtechceu.gtceu.api.fluids.FluidBuilder().temperature(0).customStill())
                .color(0xffffff)
                .flags(DISABLE_DECOMPOSITION, DISABLE_MATERIAL_RECIPES).buildAndRegister();
        GravitonShard = new Material.Builder(GTNACORE.id("graviton_shard")).langValue("Graviton Shard").gem()
                .color(0xffffff).iconSet(GodforgeIconSets.GRAVITON_SHARD)
                .flags(DISABLE_DECOMPOSITION, DISABLE_MATERIAL_RECIPES).buildAndRegister();
        addPlasmas();
    }
}
