"""Extract the GTNH Forge of Gods English strings into GTNA's lang provider.

Usage: python3 tools/extract_godforge_lang.py <GT5-Unofficial checkout>

Source: GT5-Unofficial a3e1e11241a814c9fa0dd0973d5699548428f689 (LGPL-3.0),
src/main/resources/assets/tectech/lang/en_US.lang. Keys are renamed into the gtna namespace:
  gt.blockmachines.multimachine.FOG.*   -> gtna.godforge.gui.*
  fog.*                                 -> gtna.godforge.*
  tt.godforge.star_color.preset.*       -> gtna.godforge.star_color.preset.*
"""

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/main/java/com/raishxn/gtna/data/lang/GodforgeLang.java"
PREFIXES = (
    ("gt.blockmachines.multimachine.FOG.", "gtna.godforge.gui."),
    ("fog.", "gtna.godforge."),
    ("tt.godforge.star_color.preset.", "gtna.godforge.star_color.preset."),
)
SKIP = ("fog.debug.",)


def rename(key):
    for old, new in PREFIXES:
        if key.startswith(old):
            return new + key[len(old):]
    return None


def java(text):
    text = text.replace("\\n", "\n")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main():
    lang = Path(sys.argv[1]) / "src/main/resources/assets/tectech/lang/en_US.lang"
    entries = []
    for line in lang.read_text(encoding="utf-8").splitlines():
        if "=" not in line or line.startswith("#"):
            continue
        key, value = line.split("=", 1)
        if key.startswith(SKIP):
            continue
        new = rename(key)
        if new:
            entries.append((new, value.replace("%%", "%%")))
    body = "\n".join(f"        provider.add({java(k)}, {java(v)});" for k, v in entries)
    OUT.write_text(f"""package com.raishxn.gtna.data.lang;

import com.raishxn.gtna.data.GTNALangProvider;

/**
 * Forge of Gods GUI strings from GTNH TecTech en_US.lang (GT5-Unofficial a3e1e112, LGPL-3.0), generated by
 * tools/extract_godforge_lang.py. Do not edit by hand.
 */
public final class GodforgeLang {{

    private GodforgeLang() {{}}

    public static void add(GTNALangProvider provider) {{
{body}
    }}
}}
""", encoding="utf-8")
    print(f"wrote {len(entries)} entries to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
