"""GTNH Forge of Gods tooltip text (forge-of-gods.md, godforge-*-module.md, ItemCasingsGodforge) in EN and PT-BR."""
HR = "§b§m" + " " * 72
EN = {
    "gtna.godforge.machine_type.stellar_forge": "Stellar Forge",
    "gtna.godforge.machine_type.blast_furnace": "Blast Furnace, Furnace",
    "gtna.godforge.machine_type.blast_smelter": "Blast Smelter",
    "gtna.godforge.machine_type.plasma_fabricator": "Plasma Fabricator",
    "gtna.godforge.machine_type.exotic_matter_producer": "Exotic Matter Producer",
    "gtna.machine.forge_of_gods.tooltip": [
        "§7§oAlso known as Godforge or Gorge for short", HR,
        "§7A massive structure harnessing the thermal, gravitational and",
        "§7kinetic energy of a stabilized neutron star for material processing",
        "§7This multiblock can house §cup to 16 modules §7which utilize the star to energize materials",
        "§7to varying degrees, ranging from regular smelting to matter degeneration",
        "§7EU requirements for all modules are handled via wireless energy directly", HR,
        "§7This multiblock has an §6extensive upgrade tree §7which influences all of its functions,",
        "§7such as §6unlocking new module types§7, §6increasing heat levels §7and §6granting",
        "§6various processing speed bonuses§7. These upgrades can be unlocked by reaching",
        "§7certain milestones and/or spending materials", HR,
        "§aClicking on the logo in the controller gui opens an extensive information window§7,",
        "§7explaining everything there is to know about this multiblock"],
    "gtna.machine.godforge_smelting_module.tooltip": [
        "§7This is a module of the Godforge", "§7Must be part of a Godforge to function",
        "§7Used for basic smelting operations at various temperatures", HR,
        "§7As the first of the Godforge modules, this module performs the most basic",
        "§7thermal processing, namely smelting materials identically to a furnace or blast furnace",
        "§7The desired method of processing can be selected in the gui",
        "§7This module is specialized towards speed and high heat levels"],
    "gtna.machine.godforge_molten_module.tooltip": [
        "§7This is a module of the Godforge", "§7Must be part of a Godforge to function",
        "§7Used for high temperature material liquefaction", HR,
        "§7The second module of the Godforge, this module melts materials directly into",
        "§7their liquid form. If an output material does not have a liquid form, it will be output",
        "§7as a regular solid instead",
        "§7This module is specialized towards parallel processing"],
    "gtna.machine.godforge_plasma_module.tooltip": [
        "§7This is a module of the Godforge", "§7Must be part of a Godforge to function",
        "§7Used for extreme temperature matter ionization", HR,
        "§7The third module of the Godforge, this module infuses materials with extreme amounts",
        "§7of heat, ionizing and turning them into plasma directly. Not all plasmas can be produced",
        "§7right away, some of them require certain upgrades to be unlocked",
        "§7This module is specialized towards energy and overclock efficiency"],
    "gtna.machine.godforge_exotic_module.tooltip": [
        "§7This is a module of the Godforge", "§7Must be part of a Godforge to function",
        "§7Used for ultra high temperature matter degeneration", HR,
        "§7The fourth and final module of the Godforge, this module breaks apart the very",
        "§7building blocks of matter, producing exotic mixtures in the process. Quark-Gluon Plasma",
        "§7can be manufactured right away, but production of Magnetic Monopole Matter (Magmatter)",
        "§7requires a fully upgraded Godforge",
        "§7This module is specialized towards acquisition of unique materials"],
}
PT = {
    "gtna.godforge.machine_type.stellar_forge": "Forja Estelar",
    "gtna.godforge.machine_type.blast_furnace": "Alto-Forno, Fornalha",
    "gtna.godforge.machine_type.blast_smelter": "Fundidor de Liga",
    "gtna.godforge.machine_type.plasma_fabricator": "Fabricador de Plasma",
    "gtna.godforge.machine_type.exotic_matter_producer": "Produtor de Matéria Exótica",
    "gtna.machine.forge_of_gods.tooltip": [
        "§7§oTambém conhecida como Godforge, ou Gorge para os íntimos", HR,
        "§7Uma estrutura colossal que aproveita a energia térmica, gravitacional e",
        "§7cinética de uma estrela de nêutrons estabilizada para processar materiais",
        "§7Esta estrutura comporta §caté 16 módulos §7que usam a estrela para energizar materiais",
        "§7em diferentes graus, da fundição comum até a degeneração da matéria",
        "§7O EU de todos os módulos vem diretamente da energia sem fio", HR,
        "§7Esta estrutura tem uma §6extensa árvore de melhorias §7que influencia todas as suas funções,",
        "§7como §6desbloquear novos tipos de módulo§7, §6aumentar os níveis de calor §7e §6conceder",
        "§6vários bônus de velocidade de processamento§7. Essas melhorias são liberadas alcançando",
        "§7certos marcos e/ou gastando materiais", HR,
        "§aClicar no logo da GUI do controlador abre uma janela de informações completa§7,",
        "§7explicando tudo o que há para saber sobre esta estrutura"],
    "gtna.machine.godforge_smelting_module.tooltip": [
        "§7Este é um módulo da Godforge", "§7Precisa fazer parte de uma Godforge para funcionar",
        "§7Usado em operações básicas de fundição em várias temperaturas", HR,
        "§7Primeiro dos módulos da Godforge, este módulo faz o processamento térmico",
        "§7mais básico: fundir materiais exatamente como uma fornalha ou um alto-forno",
        "§7O método de processamento é escolhido na GUI",
        "§7Este módulo é especializado em velocidade e altos níveis de calor"],
    "gtna.machine.godforge_molten_module.tooltip": [
        "§7Este é um módulo da Godforge", "§7Precisa fazer parte de uma Godforge para funcionar",
        "§7Usado na liquefação de materiais em alta temperatura", HR,
        "§7O segundo módulo da Godforge funde os materiais direto na forma líquida.",
        "§7Se um material de saída não tiver forma líquida, ele sai",
        "§7como sólido comum",
        "§7Este módulo é especializado em processamento paralelo"],
    "gtna.machine.godforge_plasma_module.tooltip": [
        "§7Este é um módulo da Godforge", "§7Precisa fazer parte de uma Godforge para funcionar",
        "§7Usado na ionização de matéria em temperaturas extremas", HR,
        "§7O terceiro módulo da Godforge infunde quantidades extremas de calor nos materiais,",
        "§7ionizando-os e transformando-os direto em plasma. Nem todos os plasmas podem ser",
        "§7produzidos de início: alguns exigem melhorias específicas",
        "§7Este módulo é especializado em eficiência de energia e de overclock"],
    "gtna.machine.godforge_exotic_module.tooltip": [
        "§7Este é um módulo da Godforge", "§7Precisa fazer parte de uma Godforge para funcionar",
        "§7Usado na degeneração de matéria em temperaturas ultra-altas", HR,
        "§7O quarto e último módulo da Godforge quebra os próprios blocos fundamentais da",
        "§7matéria, produzindo misturas exóticas no processo. Plasma de Quarks e Glúons pode ser",
        "§7produzido de imediato, mas a Matéria de Monopolos Magnéticos (Magmatéria)",
        "§7exige uma Godforge totalmente melhorada",
        "§7Este módulo é especializado na obtenção de materiais únicos"],
}
BLOCKS = {  # id -> (EN name, GTNH casing tooltip index or None)
    "singularity_reinforced_stellar_shielding_casing": ("Singularity Reinforced Stellar Shielding Casing", 0),
    "celestial_matter_guidance_casing": ("Celestial Matter Guidance Casing", 1),
    "boundless_gravitationally_severed_structure_casing": ("Boundless Gravitationally Severed Structure Casing", 2),
    "transcendentally_amplified_magnetic_confinement_casing": ("Transcendentally Amplified Magnetic Confinement Casing", 3),
    "stellar_energy_siphon_casing": ("Stellar Energy Siphon Casing", 4),
    "remote_graviton_flow_modulator": ("Remote Graviton Flow Modulator", 5),
    "medial_graviton_flow_modulator": ("Medial Graviton Flow Modulator", 6),
    "central_graviton_flow_modulator": ("Central Graviton Flow Modulator", 7),
    "harmonic_phonon_transmission_conduit": ("Harmonic Phonon Transmission Conduit", 8),
    "spatially_transcendent_gravitational_lens": ("Spatially Transcendent Gravitational Lens", "glass"),
    "hypogen_coil": ("Hypogen Coil Block", None),
}
CASING_EN = {
    0: ("Shielded by the event horizon of a singularity", "Don't get too close..."),
    1: ("Designed to route stellar matter using spacetime distortion", "Reality Distortion"),
    2: ("Unaffected by gravitational forces", "Not even a black hole could tear it apart."),
    3: ("Creates enormous magnetic fields capable of constraining entire stars", "It's super effective!"),
    4: ("Taps into streams of stellar matter to harness their heat energy", "Turn up the heat!"),
    5: ("Controls the flow of gravitons to manipulate gravity", "Exponential scaling past 800 Galaxies"),
    6: ("Controls the flow of gravitons to manipulate gravity", "Getting closer..."),
    7: ("Controls the flow of gravitons to manipulate gravity", "Gravity Central"),
    8: ("Transfers and stores extreme amounts of heat without any loss", "<<<Thermal<<< >>>Wave>>>"),
    "glass": ("Gravitational lensing taken literal", "GraviLens 9000!"),
}
CASING_PT = {
    0: ("Blindado pelo horizonte de eventos de uma singularidade", "Não chegue muito perto..."),
    1: ("Projetado para guiar matéria estelar usando distorção do espaço-tempo", "Distorção da Realidade"),
    2: ("Imune às forças gravitacionais", "Nem um buraco negro conseguiria despedaçá-lo."),
    3: ("Cria campos magnéticos enormes, capazes de conter estrelas inteiras", "É super efetivo!"),
    4: ("Capta correntes de matéria estelar para aproveitar sua energia térmica", "Aumente o calor!"),
    5: ("Controla o fluxo de grávitons para manipular a gravidade", "Escala exponencial depois de 800 Galáxias"),
    6: ("Controla o fluxo de grávitons para manipular a gravidade", "Chegando mais perto..."),
    7: ("Controla o fluxo de grávitons para manipular a gravidade", "Central da Gravidade"),
    8: ("Transfere e armazena quantidades extremas de calor sem nenhuma perda", "<<<Onda<<< >>>Térmica>>>"),
    "glass": ("Lente gravitacional levada ao pé da letra", "GraviLente 9000!"),
}
