PT = {
"gtna.godforge.upgrade.text.0": "Desbloqueia a funcionalidade básica da Forja dos Deuses: 8 vagas de módulo, 1 anel, o módulo Forja de Energia Helioflare, 2 bilhões de EU/t de tensão de processamento e limite de bônus de calor de 15.000K.",
"gtna.godforge.upgrade.text.1": "Desbloqueia um multiplicador de redução do tempo de receita baseado no calor atual da máquina. O bônus é calculado pela fórmula: Multiplicador = 1 / (Calor^0,01)",
"gtna.godforge.upgrade.text.2": "Aumenta a eficiência de combustível multiplicando o consumo real de combustível por 0,8",
"gtna.godforge.upgrade.text.3": "Multiplica o consumo máximo de combustível por 1,2",
"gtna.godforge.upgrade.text.4": "Aumenta a tensão base de processamento de todos os módulos em: Unidades de Combustível Estelar/s * 10^8 EU/t",
"gtna.godforge.upgrade.text.5": "Desbloqueia o módulo Núcleo de Fusão Helioflux.",
"gtna.godforge.upgrade.text.6": "Desbloqueia um multiplicador do paralelo máximo baseado na taxa de consumo de combustível. O bônus é calculado pela fórmula: Multiplicador = 1 + (Unidades de Combustível Estelar/s) / 15",
"gtna.godforge.upgrade.text.7": "Desbloqueia o módulo Fabricador de Plasma Heliotérmico e o processamento básico de elemento -> plasma (plasmas de 1 etapa, no máximo fusão T3).",
"gtna.godforge.upgrade.text.8": "Desbloqueia uma janela de configuração do tamanho máximo da bateria e aumenta o limite para o máximo de int. Além disso, desbloqueia um desconto de energia que escala com o tamanho da bateria (limitado a 0,05, ou 5%%). O desconto é calculado assim: Desconto = (1 - 1,05^(-0,05 * Capacidade Máxima da Bateria)) / 20",
"gtna.godforge.upgrade.text.9": "Aumenta o consumo máximo de combustível em 1 Unidade de Combustível Estelar/s para cada melhoria comprada.",
"gtna.godforge.upgrade.text.10": "Adiciona um multiplicador x2 ao paralelo máximo.",
"gtna.godforge.upgrade.text.11": "Desbloqueia o módulo Exotizador Heliofusão e a criação de plasma de quarks e glúons. Neste ponto o módulo não é afetado por nenhum outro multiplicador ou bônus de outras melhorias.",
"gtna.godforge.upgrade.text.12": "Melhora a fórmula de conversão consumo de combustível -> calor. Fórmula melhorada: Calor da Forja de Energia = log_1,12(Unidades de Combustível Estelar/s) * 1000 + 12601, Calor do Núcleo de Fusão = log_1,18(Unidades de Combustível Estelar/s) * 1000 + 12601",
"gtna.godforge.upgrade.text.13": "Melhora a fórmula do SA para: Multiplicador = 1 + (Unidades de Combustível Estelar/s) / 5",
"gtna.godforge.upgrade.text.14": "Permite que o fator de OC escale com o calor atual. Forjas de Energia e Núcleos de Fusão ganham um fator de OC fixo de 2,15. Fator de OC do Fabricador de Plasma = 4 - 25000 / Calor",
"gtna.godforge.upgrade.text.15": "Permite que o Fabricador de Plasma Heliotérmico processe plasmas de múltiplas etapas. A restrição de tier continua valendo.",
"gtna.godforge.upgrade.text.16": "Permite que a Forja de Energia Helioflare receba todos os benefícios do caminho de melhorias do Núcleo de Fusão Helioflux.",
"gtna.godforge.upgrade.text.17": "Aumenta o limite dos bônus de calor do EBF para 30.000K.",
"gtna.godforge.upgrade.text.18": "Desbloqueia um multiplicador do paralelo máximo baseado no calor atual. O bônus é calculado pela fórmula: Multiplicador = 1 + Calor / 15000",
"gtna.godforge.upgrade.text.19": "Melhora o bônus de redução de energia por calor do EBF de 5%% para 8%% e adiciona um desconto de energia baseado no nível de carga da bateria interna. O bônus é calculado pela fórmula: Desconto = (Carga atual / Capacidade Máxima - 0,5)^2 * (-0,6) + 0,15, multiplicado por 2/3 para módulos que não sejam o Fabricador de Plasma",
"gtna.godforge.upgrade.text.20": "Os bônus de calor do EBF são concedidos acima de 30.000K, mas o calor usado nos cálculos de bônus é determinado pela fórmula: Calor da Forja de Energia = 30000 + (Calor Atual - 30000)^0,85, Calor do Núcleo de Fusão = 30000 + (Calor Atual - 30000)^0,8",
"gtna.godforge.upgrade.text.21": "Desbloqueia um multiplicador do paralelo máximo baseado no total de melhorias compradas. O bônus é calculado pela fórmula: Multiplicador = 1 + Quantidade de Melhorias / 5",
"gtna.godforge.upgrade.text.22": "Melhora o IGCC com base no paralelo máximo atual. Fórmula melhorada: Multiplicador = (1 / Calor^0,01) / (Paralelo^0,02)",
"gtna.godforge.upgrade.text.23": "Multiplica a tensão máxima de processamento por 4 a cada anel ativo, aplicado depois dos outros bônus.",
"gtna.godforge.upgrade.text.24": "Permite que o Fabricador de Plasma Heliotérmico processe plasmas até T5.",
"gtna.godforge.upgrade.text.25": "Permite que o Exotizador Heliofusão seja afetado pelos benefícios das outras melhorias, mas esses benefícios passam primeiro por raiz quadrada. O bônus de overclock é ajustado pela fórmula: Fator de OC = 2 + (Fator de OC Base - 2)^2",
"gtna.godforge.upgrade.text.26": "Permite construir o segundo anel e adiciona 4 vagas de módulo.",
"gtna.godforge.upgrade.text.27": "Remove o limite do consumo máximo de combustível, mas o consumo usado nos cálculos de bônus escala pela fórmula: CC Real = CC Máx Atual + (CC Atual - CC Máx Atual)^0,4, onde CC é o consumo de combustível e CC máx é o consumo máximo sem esta melhoria. O consumo de combustível não pode passar de 2^31 por razões técnicas.",
"gtna.godforge.upgrade.text.28": "Remove o limite da tensão máxima de processamento. A tensão pode ser definida na GUI de cada módulo.",
"gtna.godforge.upgrade.text.29": "Desbloqueia a produção de Magmatéria no Exotizador Heliofusão e a criação de plasmas exóticos no Fabricador de Plasma Heliotérmico.",
"gtna.godforge.upgrade.text.30": "Permite construir o terceiro anel, adiciona 4 vagas de módulo e desbloqueia a ejeção e a injeção de Fragmentos de Grávitons.",
"gtna.godforge.button.fuelconfig.tooltip": "Menu de Configuração de Combustível",
"gtna.godforge.button.upgradetree.tooltip": "Caminho da Transcendência Celestial",
"gtna.godforge.button.furnacemode.tooltip.01": "Modo Alto-Forno",
"gtna.godforge.button.furnacemode.tooltip.02": "Modo Fornalha",
"gtna.godforge.button.magmattermode.tooltip.01": "Modo Plasma de Quarks e Glúons",
"gtna.godforge.button.magmattermode.tooltip.02": "Modo Magmatéria",
"gtna.godforge.button.magmattermode.tooltip.03": "Modo Magmatéria bloqueado, falta a melhoria",
"gtna.godforge.button.battery.tooltip.01": "Alternar Carregamento da Bateria",
"gtna.godforge.button.battery.tooltip.02": "Clique direito para abrir o menu de configuração (se desbloqueado)",
"gtna.godforge.button.voltageconfig.tooltip.01": "Abrir configuração de tensão",
"gtna.godforge.button.voltageconfig.tooltip.02": "Configuração de tensão bloqueada, requer O Fluxo Ilimitado (melhoria)",
"gtna.godforge.button.structurecheck.tooltip": "Atualizar o status de conexão dos módulos",
"gtna.godforge.button.milestones.tooltip": "Visão Geral dos Marcos",
"gtna.godforge.button.materialrequirements.tooltip": "A melhoria precisa de materiais adicionais",
"gtna.godforge.button.materialrequirementsmet.tooltip": "Todos os materiais fornecidos",
"gtna.godforge.button.materialrequirements.tooltip.clickhere": "Clique para abrir a janela de inserção de materiais",
"gtna.godforge.button.ejection.tooltip": "Alternar Ejeção de Fragmentos de Grávitons",
"gtna.godforge.button.formatting.tooltip": "Alternar Formatação de Números",
"gtna.godforge.button.exoticinputs.tooltip": "Clique para mostrar as entradas esperadas",
"gtna.godforge.button.possibleexoticinputs.tooltip": "Clique para mostrar todas as entradas possíveis",
"gtna.godforge.button.reciperefresh.tooltip": "Clique para reiniciar a receita",
"gtna.godforge.button.refreshtimer.tooltip": "Reinício disponível em",
"gtna.godforge.button.seconds": "Segundos",
"gtna.godforge.button.thanks.tooltip": "Lista de Contribuidores",
"gtna.godforge.button.color.tooltip": "Menu de Cosméticos",
"gtna.godforge.button.statistics.tooltip": "Visão Geral das Estatísticas",
"gtna.godforge.text.tooltip.heat": "Valor de calor usado para checar se uma receita pode rodar",
"gtna.godforge.text.tooltip.effectiveheat": "Valor de calor usado para calcular os bônus",
"gtna.godforge.text.tooltip.parallel": "Quantidade máxima de paralelos",
"gtna.godforge.text.tooltip.speedbonus": "Multiplicador do tempo base da receita, tornando-a mais curta",
"gtna.godforge.text.tooltip.energydiscount": "Multiplicador do uso base de energia, reduzindo-o",
"gtna.godforge.text.tooltip.ocdivisor": "Divisor da redução de tempo da receita por overclock (não afeta OCs perfeitos)",
"gtna.godforge.text.tooltip.processingvoltage": "Tensão base de processamento das receitas",
"gtna.godforge.text.tooltip.factorpreview": "Digite um fator de combustível para simular os cálculos",
"gtna.godforge.text.tooltip.applysimulationchanges": "Simular novos valores",
"gtna.godforge.text.tooltip.voltageadjustment": "Por causa de risco de overflow, a tensão real segue esta fórmula:",
"gtna.godforge.text.tooltip.voltageadjustment.1": "Tensão = Mín(Tensão Escolhida, 2^63 / Paralelo Máximo)",
"gtna.godforge.gui.parallel": "Paralelo",
"gtna.godforge.gui.batch": "Tamanho do Lote",
"gtna.godforge.gui.fuelconsumption": "Fator de Consumo de Combustível Estelar",
"gtna.godforge.gui.fuelinfo.0": "O Fator de Consumo de Combustível Estelar é o principal fator no cálculo do consumo total de combustível estelar por segundo. Cada tipo de combustível escala de forma diferente:",
"gtna.godforge.gui.fuelinfo.1": "Resíduo Dimensionalmente Transcendente: fator*300*1,15^fator",
"gtna.godforge.gui.fuelinfo.2": "Mistura Condensada de Plasma Estelar Bruto: fator*2*1,08^fator",
"gtna.godforge.gui.fuelinfo.3": "Matéria Estelar Magneto-hidrodinamicamente Contida: fator/25",
"gtna.godforge.gui.fuelinfo.4": "Este fator também determina o calor base da estrutura: Calor=log_1,5(fator)*1000+12601",
"gtna.godforge.gui.fuelinfo.5": "Melhorias podem alterar essas fórmulas; as mudanças estão listadas nas descrições das respectivas melhorias.",
"gtna.godforge.gui.fueltype": "Clique para Escolher o Tipo de Combustível",
"gtna.godforge.gui.fuelusage": "Uso de Combustível",
"gtna.godforge.gui.plasmamultistep": "Plasma de múltiplas etapas: %s",
"gtna.godforge.gui.plasmarecipetier": "Tier de Fusão: %s",
"gtna.godforge.gui.storedfuel": "Combustível armazenado:",
"gtna.godforge.gui.storedstartupfuel": "Combustível Estelar de partida:",
"gtna.godforge.gui.batteryinfo": "Definir tamanho da bateria",
"gtna.godforge.gui.shardcost": "Custo em Fragmentos de Grávitons:",
"gtna.godforge.gui.availableshards": "Fragmentos de Grávitons disponíveis:",
"gtna.godforge.gui.modulestatus": "Status:",
"gtna.godforge.gui.modulestatus.true": "Conectado",
"gtna.godforge.gui.modulestatus.false": "Desconectado",
"gtna.godforge.gui.voltageinfo": "Tensão por Paralelo",
"gtna.godforge.gui.totalprogress": "Progresso Total",
"gtna.godforge.gui.milestoneprogress": "Nível Atual do Marco",
"gtna.godforge.gui.progress": "Próximo Marco em",
"gtna.godforge.gui.milestonecomplete": "Marco Concluído",
"gtna.godforge.gui.milestoneinfo": "Ver Progresso dos Marcos",
"gtna.godforge.gui.inversionactive": "Inversão Ativa",
"gtna.godforge.gui.expectedinputs": "Entradas Esperadas",
"gtna.godforge.gui.possibleinputsqgp": "Materiais de Entrada Possíveis para QGP",
"gtna.godforge.gui.possibleinputsmagmatter": "Materiais de Entrada Possíveis para Magmatéria",
"gtna.godforge.gui.powermilestone": "Carga",
"gtna.godforge.gui.recipemilestone": "Conversão",
"gtna.godforge.gui.fuelmilestone": "Catalisador",
"gtna.godforge.gui.purchasablemilestone": "Composição",
"gtna.godforge.gui.power": "EU Consumidos",
"gtna.godforge.gui.recipes": "Receitas Processadas",
"gtna.godforge.gui.fuelconsumed": "Unidades de Combustível Consumidas",
"gtna.godforge.gui.extensions": "Extensões Construídas",
"gtna.godforge.gui.shardgain": "Fragmentos de Grávitons obtidos",
"gtna.godforge.gui.payUpgradeCosts": "Pagar Custo da Melhoria",
"gtna.godforge.gui.consumeUpgradeMats": "Clique para consumir os materiais da melhoria",
"gtna.godforge.gui.clickhere": "Confuso? Clique aqui para informações gerais",
"gtna.godforge.gui.introduction": "§NIntrodução",
"gtna.godforge.gui.introductioninfotext": "Muita coisa acontece na Forja dos Deuses, o que pode confundir no começo. Este menu explica tudo o que está acontecendo e todas as capacidades e mecânicas da forja.",
"gtna.godforge.gui.tableofcontents": "§NSumário",
"gtna.godforge.gui.fuel": "Combustível",
"gtna.godforge.gui.modules": "Módulos",
"gtna.godforge.gui.upgrades": "Melhorias",
"gtna.godforge.gui.milestones": "Marcos",
"gtna.godforge.gui.inversion": "Inversão",
}
