PT = {
"gtna.godforge.gui.fuelinfotext.1": "Depois que a estrutura da Forja é construída e formada, apenas ligá-la não basta para que funcione. A Forja precisa receber uma certa quantidade de §bCombustível Estelar §6(o item) para realmente iniciar.",
"gtna.godforge.gui.fuelinfotext.2": "A quantidade de Combustível Estelar necessária depende do fator de consumo atual, que pode ser definido no menu de configuração de combustível. Por padrão o máximo é 5, mas pode ser aumentado depois com melhorias. O Combustível Estelar escala assim:",
"gtna.godforge.gui.fuelinfotext.3": "fator*25*1,2^fator",
"gtna.godforge.gui.fuelinfotext.4": "O Combustível Estelar pode ser fornecido por um barramento de entrada; ele é consumido periodicamente e armazenado internamente. Quando há Combustível Estelar suficiente armazenado, a estrutura liga de verdade (permitindo que os módulos se conectem) e converte o Combustível Estelar consumido em §bCombustível Estelar Líquido§6 armazenado.",
"gtna.godforge.gui.fuelinfotext.5": "A partir daí, a Forja precisa ser abastecida com um dos combustíveis líquidos (o tipo pode ser escolhido no menu de configuração de combustível). Se não houver combustível suficiente do tipo escolhido na escotilha de entrada, a quantidade armazenada diminui e, se chegar a 0, a Forja volta ao estado 'desligado', em que os módulos se desconectam e ela precisa receber Combustível Estelar de novo.",
"gtna.godforge.gui.fuelinfotext.6": "A quantidade de Combustível Estelar (líquido) armazenada internamente pode ser aumentada ativando o §bCarregamento da Bateria§6; isso dobra o uso de combustível, mas metade dele é guardada na bateria interna.",
"gtna.godforge.gui.moduleinfotext.1": "Há 4 tipos de módulos que podem ser usados na Forja: a Forja de Energia Helioflare, o Núcleo de Fusão Helioflux, o Fabricador de Plasma Heliotérmico e o Exotizador Heliofusão. Esses módulos são estruturas separadas que precisam ser construídas nos locais designados da estrutura da Forja.",
"gtna.godforge.gui.moduleinfotext.2": "Depois de construídos, os módulos precisam se conectar à Forja, o que acontece automaticamente se todos os requisitos do módulo forem atendidos. Também há um botão para atualizar o status sem esperar o temporizador. Cada módulo tem sua função e seus requisitos específicos e é afetado de forma diferente por certas melhorias.",
"gtna.godforge.gui.moduleinfotext.forge.1": "Forja de Energia Helioflare",
"gtna.godforge.gui.moduleinfotext.forge.2": "O primeiro módulo desbloqueado, basicamente um alto-forno ainda mais poderoso que a Fornalha Exotérmica. Além disso, este módulo tem um §bModo Fornalha§6, que o transforma em um Multi Fundidor hiperpoderoso. Este módulo vem desbloqueado por padrão e tem §b1024§6 paralelos base.",
"gtna.godforge.gui.moduleinfotext.core.1": "Núcleo de Fusão Helioflux",
"gtna.godforge.gui.moduleinfotext.core.2": "O segundo módulo desbloqueado, que também processa receitas de alto-forno, mas com uma diferença: as saídas saem em §bforma fundida§6 em vez de lingotes. Se uma saída não tem forma fundida, sai na forma normal. Este módulo precisa ser desbloqueado por uma melhoria para funcionar e tem §b512§6 paralelos base.",
"gtna.godforge.gui.moduleinfotext.fab.1": "Fabricador de Plasma Heliotérmico",
"gtna.godforge.gui.moduleinfotext.fab.2": "O terceiro módulo desbloqueado, com um mapa de receitas próprio de conversão direta de material em plasma. Essas receitas são agrupadas por duas propriedades, §bTier de Fusão§6 e §bEtapas Necessárias§6, que limitam quais receitas podem ser processadas antes de as melhorias correspondentes serem desbloqueadas. Diferente da fusão comum, essas receitas produzem o plasma do material de entrada. Este módulo tem §b512§6 paralelos base.",
"gtna.godforge.gui.moduleinfotext.exotic.1": "Exotizador Heliofusão",
"gtna.godforge.gui.moduleinfotext.exotic.2": "O quarto e último módulo desbloqueado, capaz de produzir §bPlasma de Quarks e Glúons§6 e depois §bMagmatéria§6. Este módulo tem desafios de automação próprios para cada material, então é recomendado ter dois, já que cada um precisa ficar travado em um dos materiais.",
"gtna.godforge.gui.moduleinfotext.exotic.3": "A regra comum aos desafios dos dois modos é: o módulo libera materiais no início de um ciclo de receita e espera as entradas corretas chegarem antes de começar o processamento do material de saída.",
"gtna.godforge.gui.moduleinfotext.exotic.4": "Ao produzir §bPlasma de Quarks e Glúons§6, o módulo libera até 7 fluidos/pós diferentes, em quantidades de 1-64 e 1-7 respectivamente, e os plasmas correspondentes nessas quantidades precisam ser devolvidos para a receita rodar. Para cada L de fluido, um balde de plasma, e para cada pó, 9 lingotes de plasma precisam ser devolvidos.",
"gtna.godforge.gui.moduleinfotext.exotic.5": "Se o §bModo Magmatéria§6 estiver ativo, o desafio muda. O módulo libera 1-50L de §bFluido Temporal Rico em Táquions§6, 51-100L de §bFluido Espacialmente Ampliado§6 e um pó de um material de tier alto. O desafio é devolver os dois fluidos, mais tanto plasma do material do pó (em lingotes) quanto a diferença entre as quantidades de Fluido Espacialmente Ampliado e de Fluido Rico em Táquions. Quando tudo for devolvido nas quantidades certas, a receita começa e produz Magmatéria.",
"gtna.godforge.gui.moduleinfotext.exotic.6": "Este módulo tem §b64§6 paralelos base.",
"gtna.godforge.gui.upgradeinfotext.1": "As melhorias são o coração e a alma da Forja: elas desbloqueiam a maior parte de suas funções e de seu poder de processamento. A §bÁrvore de Melhorias§6 pode ser acessada pelo botão na GUI principal, e cada nó pode ser clicado para ver seus efeitos e requisitos.",
"gtna.godforge.gui.upgradeinfotext.2": "Em geral, cada melhoria só pode ser desbloqueada se a anterior estiver desbloqueada e houver §bFragmentos de Grávitons§6 suficientes. A exceção é a primeira melhoria, que não tem anterior. Algumas melhorias também têm custos extras de materiais, indicados ao lado do botão de desbloqueio quando existem.",
"gtna.godforge.gui.upgradeinfotext.3": "Se uma melhoria tem mais de uma melhoria anterior ligada, há duas opções. Ela exige:",
"gtna.godforge.gui.upgradeinfotext.4": "- Todas as melhorias anteriores (conexões §4Vermelhas§a)\n- Pelo menos uma melhoria anterior (conexões §9Azuis§a)",
"gtna.godforge.gui.upgradeinfotext.5": "Melhorias podem ser reembolsadas com o botão §bReembolsar§6, mas só se TODAS as melhorias posteriores ligadas não estiverem ativas.",
"gtna.godforge.gui.upgradeinfotext.6": "O bloco de melhorias depois do desbloqueio do Exotizador Heliofusão é especial: é o que se chama de §bA Divisão§6. Como o nome sugere, só um dos três caminhos pode ser escolhido no início, e os outros ficam bloqueados. Cada caminho tem bônus focados em um módulo específico e afeta os outros tipos com efeito reduzido (salvo indicação). A quantidade de caminhos desbloqueáveis depende da §bQuantidade de Anéis§6 da Forja, que por sua vez é limitada por melhorias posteriores.",
"gtna.godforge.gui.milestoneinfotext.1": "Os marcos são essenciais para melhorar a Forja, pois são a fonte de §bFragmentos de Grávitons§6, a moeda principal para desbloquear melhorias. Em essência, marcos são exatamente o que o nome diz: limites que, quando atingidos, concedem Fragmentos de Grávitons.",
"gtna.godforge.gui.milestoneinfotext.2": "Há quatro tipos de marcos – Carga, Conversão, Catalisador e Composição –, cada um ligado a uma estatística da Forja. Cada marco tem §bsete§6 níveis, cada um mais difícil que o anterior, mas concedendo mais Fragmentos. O primeiro nível concede 1 Fragmento, o segundo 2, o terceiro 3 e assim por diante.",
"gtna.godforge.gui.milestoneinfotext.3": "O marco de §bCarga§6 escala com o consumo total de energia de todos os módulos somados; o primeiro nível é desbloqueado com §b1e15§6 EU consumidos, e cada nível seguinte escala em §b9x§6.",
"gtna.godforge.gui.milestoneinfotext.4": "O marco de §bConversão§6 escala com o total de receitas processadas em todos os módulos (sem contar o modo fornalha da Forja de Energia Helioflare); o primeiro nível é desbloqueado com §b10M§6 de receitas processadas. Os níveis seguintes escalam em §b4x§6.",
"gtna.godforge.gui.milestoneinfotext.5": "O marco de §bCatalisador§6 se baseia no consumo de combustível da Forja, contado em unidades de Combustível Estelar (o número digitado no menu de combustível). O primeiro nível exige consumir §b10.000§6 unidades, e cada nível acima escala em §b3x§6.",
"gtna.godforge.gui.milestoneinfotext.6": "Por último, o marco de §bComposição§6 funciona um pouco diferente, pois escala com a estrutura da Forja. Níveis são concedidos para cada tipo único de módulo presente na estrutura (Exotizadores nos modos Quarks e Glúons e Magmatéria contam como tipos diferentes) e para cada anel adicional construído.",
"gtna.godforge.gui.milestoneinfotext.7": "Sua pesquisa sugere que algo estranho pode acontecer se todos os marcos chegarem ao nível final... Volte para conferir!",
"gtna.godforge.gui.inversioninfotext.1": "Quando todos os marcos da Forja chegam ao §bNível 7§6, a inversão é ativada. Isso remove o nível máximo de todos os marcos e permite que escalem §binfinitamente§6.",
"gtna.godforge.gui.inversioninfotext.2": "A escala de cada marco muda de exponencial para linear, mas a quantidade de Fragmentos concedida continua aumentando. O progresso necessário para cada marco seguinte é o mesmo exigido pelo §b7º nível§6 de cada marco.",
"gtna.godforge.gui.inversioninfotext.3": "O marco de Composição é de novo uma exceção, pois continua escalando em 1 por nível, com sua própria fórmula de progresso. Cada tipo de módulo recebe um valor, de §b1§6 para a Forja de Energia Helioflare até §b5§6 para o Exotizador Heliofusão no Modo Magmatéria; então a quantidade de cada módulo presente é subtraída de 1 e multiplicada pelo seu valor. Esses valores são somados e divididos por 5, e esse é o nível final do marco além dos 7 base.",
"gtna.godforge.gui.contributors": "Contribuidores",
"gtna.godforge.gui.lead": "Líder do Projeto",
"gtna.godforge.gui.programming": "Programação",
"gtna.godforge.gui.textures": "Texturas e Estrutura",
"gtna.godforge.gui.lore": "Mestre da Lore",
"gtna.godforge.gui.rendering": "Mago da Renderização",
"gtna.godforge.gui.playtesting": "Testes",
"gtna.godforge.gui.thanks": "Um enorme obrigado a essas pessoas incríveis por ajudarem a tornar isto realidade! -Cloud",
"gtna.godforge.gui.modulestats": "Estatísticas dos Módulos",
"gtna.godforge.gui.powerforge": "Forja de Energia",
"gtna.godforge.gui.meltingcore": "Núcleo de Fusão",
"gtna.godforge.gui.plasmafab": "Fabricador de Plasma",
"gtna.godforge.gui.exoticizer": "Exotizador",
"gtna.godforge.gui.heat": "Calor",
"gtna.godforge.gui.effectiveheat": "Calor Efetivo",
"gtna.godforge.gui.speedbonus": "Bônus de Velocidade",
"gtna.godforge.gui.energydiscount": "Desconto de Energia",
"gtna.godforge.gui.ocdivisor": "Divisor de OC",
"gtna.godforge.gui.processingvoltage": "Tensão de Processamento",
"gtna.godforge.gui.factorpreview": "Prévia do Fator de Combustível:",
"gtna.godforge.gui.clickstat": "Clique para ver a composição do valor",
"gtna.godforge.gui.hint.0": "1 - Escotilhas comuns ou Revestimento de Confinamento Magnético Transcendentalmente Amplificado",
"gtna.godforge.gui.hint.1": "2 - Controladores de Módulo ou Revestimento de Blindagem Estelar Reforçada por Singularidade",
"gtna.godforge.cosmetics.header": "Cosméticos da Estrela",
"gtna.godforge.cosmetics.color": "Cor",
"gtna.godforge.cosmetics.color.red": "Vermelho",
"gtna.godforge.cosmetics.color.green": "Verde",
"gtna.godforge.cosmetics.color.blue": "Azul",
"gtna.godforge.cosmetics.color.gamma": "Gama",
"gtna.godforge.cosmetics.color.hex": "Hex:",
"gtna.godforge.cosmetics.selectcolor.tooltip.1": "Clique esquerdo para escolher esta Cor da Estrela",
"gtna.godforge.cosmetics.selectcolor.tooltip.2": "Shift + clique esquerdo para editar esta Cor da Estrela (precisa ser personalizada)",
"gtna.godforge.cosmetics.starcolor": "Cor da Estrela Personalizada",
"gtna.godforge.cosmetics.customstarcolor": "Personalizada...",
"gtna.godforge.cosmetics.misc": "Diversos",
"gtna.godforge.cosmetics.spin": "Giro",
"gtna.godforge.cosmetics.size": "Tamanho",
"gtna.godforge.cosmetics.animations": "Animações",
"gtna.godforge.cosmetics.animations.tooltip": "Pode demorar um pouco para atualizar ao alternar",
"gtna.godforge.cosmetics.cyclespeed": "Velocidade de ciclo entre as cores",
"gtna.godforge.cosmetics.onlyintegers": "Aceita Inteiros",
"gtna.godforge.cosmetics.onlydecimals": "Aceita Decimais",
"gtna.godforge.cosmetics.starcolorname": "Nome da Cor da Estrela:",
"gtna.godforge.cosmetics.starcolorname.tooltip.1": "Defina o nome desta Cor da Estrela (máx. 15 caracteres)",
"gtna.godforge.cosmetics.starcolorname.tooltip.2": "Precisa ser único! Um número será adicionado caso contrário",
"gtna.godforge.cosmetics.colorlist.tooltip.1": "Clique esquerdo para escolher esta Cor da Estrela",
"gtna.godforge.cosmetics.colorlist.tooltip.2": "Clique direito para remover esta Cor da Estrela da lista",
"gtna.godforge.cosmetics.applycolor": "Aplicar",
"gtna.godforge.cosmetics.applycolor.tooltip": "Aplicar a cor à Cor da Estrela escolhida",
"gtna.godforge.cosmetics.addcolor": "Adicionar",
"gtna.godforge.cosmetics.addcolor.tooltip": "Adicionar à lista de Cores da Estrela",
"gtna.godforge.cosmetics.resetcolor": "Redefinir",
"gtna.godforge.cosmetics.resetcolor.tooltip": "Redefinir a Cor Atual",
"gtna.godforge.cosmetics.savecolors": "Salvar",
"gtna.godforge.cosmetics.savecolors.tooltip": "Salvar esta Cor da Estrela",
"gtna.godforge.cosmetics.deletecolors": "Excluir",
"gtna.godforge.cosmetics.deletecolors.tooltip": "Excluir esta Cor da Estrela",
"gtna.godforge.cosmetics.importcolors": "Importar",
"gtna.godforge.cosmetics.importcolors.tooltip": "Importar uma Cor da Estrela a partir de texto",
"gtna.godforge.cosmetics.exportcolors": "Exportar",
"gtna.godforge.cosmetics.exportcolors.tooltip": "Copiar a Cor da Estrela exportada para a área de transferência",
"gtna.godforge.cosmetics.exportcolors.message": "Cor da Estrela exportada copiada para a área de transferência",
"gtna.godforge.cosmetics.exportcolors.failed": "Não foi possível copiar a Cor da Estrela exportada",
"gtna.godforge.cosmetics.importer.import": "Importar Cor da Estrela",
"gtna.godforge.cosmetics.importer.error": "Cor da Estrela inválida",
"gtna.godforge.cosmetics.importer.valid": "Cor da Estrela válida",
"gtna.godforge.cosmetics.importer.apply": "Aplicar",
"gtna.godforge.cosmetics.importer.apply.tooltip": "Aplicar a Cor da Estrela importada ao editor",
"gtna.godforge.cosmetics.importer.reset": "Redefinir",
"gtna.godforge.cosmetics.importer.reset.tooltip": "Redefinir a Cor da Estrela importada",
"gtna.godforge.star_color.preset.default": "Padrão",
"gtna.godforge.star_color.preset.rainbow": "Arco-íris",
"gtna.godforge.star_color.preset.clouds_pick": "Escolha do Cloud",
"gtna.godforge.star_color.preset.mayas_pick": "Escolha da Maya",
"gtna.godforge.animations.enabled": "Animações ativadas.",
"gtna.godforge.animations.disabled": "Animações desativadas.",
"gtna.godforge.info.rings": "Quantidade de Anéis: %s",
"gtna.godforge.info.upgrades": "Total de Melhorias Desbloqueadas: %s",
"gtna.godforge.info.connected": "Módulos Conectados: %s/%s",
"gtna.godforge.gui.no_extra_cost": "Nenhuma melhoria precisa de materiais extras",
"gtna.godforge.gui.battery_locked": "Requer Capacitor de Elétrons Relativísticos (melhoria)",
"gtna.godforge.gui.voltage_config": "Configuração de Tensão",
"gtna.godforge.gui.max_parallel": "Máx",
"gtna.godforge.gui.max_parallel.tooltip": "Sempre usar o paralelo máximo",
"gtna.subtitle.godforge.loop": "A Forja dos Deuses ressoa",
}
